### ISSUE TITLE
Is it possible to render as html?

### ISSUE THREAD

**Issue by atwahsz** [ahmed-mohamed-sn/olliePy#4]

**Comment by ahmed-mohamed-sn** [comment]
Yes, you can render inside jupyter by using `dashboard.serve_dashboard_from_local_server(mode='jupyter')`.

You can also save the dashboard using `dashboard.save_dashboard(zip_dashboard=False)` then you have two options:
-  Navigate to the location of the dashboard and open index.html then upload the report_data.json file.
- Navigate to the location of the dashboard and make sure you activated the python environment which has olliepy installed then use start_dashboard.bat or start_dashboard.sh which will run a flask server then serve you the dashboard.
