### ISSUE TITLE
Dataframe update while keeping dashboard layout

### ISSUE THREAD

**Issue by aysenurbilgin** [ahmed-mohamed-sn/olliePy#7]
Hi,

It would be very useful to be able to update the dashboard with new data. Do you have support plans for such a feature?

Thanks,
Ays

**Comment by ahmed-mohamed-sn** [comment]
Hi Ays,

Sure we can support this in the next version.

Best regards,
Ahmed

**Comment by ahmed-mohamed-sn** [comment]
The requested feature has been added. Please check [https://github.com/ahmed-mohamed-sn/olliePy/blob/master/examples/interactive_dashboard_example.ipynb](Interactive dashboard example) to see how to load an existing dashboard and copy its charts and number displays to a new dashboard with new data.
